name: Build QMK firmware

on: [workflow_dispatch, push]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: master
      preparation_command: |
        ls $GITHUB_WORKSPACE
        echo -------------
        cp $GITHUB_WORKSPACE/keyboards/srwi $GITHUB_WORKSPACE/qmk_firmware/keyboards/srwi

  publish:
    name: 'QMK Userspace Publish'
    uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
    if: always() && !cancelled()
    needs: build
